# Continuous Integration pipeline
# Triggers on any commit in a pull request with changes to the backend
# Tests backend to ensure no errors will be merged into master

name: Bobble Backend Test CI

# only run this test if theres any changes to the backend
on:
  pull_request:
    paths:
      - "online-shopping-website/backend/**"

jobs:
  test:
    name: Test Backend ğŸ§ª
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo ğŸ˜µ
        uses: actions/checkout@v2
      - name: Use Node.js 16.x ğŸ¥Œ
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: online-shopping-website/backend/package-lock.json
      - name: Test ğŸ¯
        run: |
          cd ./online-shopping-website/backend
          npm ci
          npm test
