name: Bobble CI

env:
  CI: false    # Used to avoid warnings turning into errors

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test and Build Bobble App ğŸ’­
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo ğŸ˜µ
      uses: actions/checkout@v2
    - name: Use Node.js 16.x ğŸ¥Œ
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: online-shopping-website/frontend/package-lock.json
    - name: npm CI, Test, Build ğŸ’ª
      run: |
        cd ./online-shopping-website/frontend
        npm ci
        npm test
        npm run build
    - name: Upload Build Output ğŸ‘†
      uses: actions/upload-artifact@v2.3.1
      with:
        name: BuildOutput
        path: online-shopping-website/frontend/build

  deploy:
    name: Deploy Bobble App to Google Cloud ğŸš€
    
    # Only runs after build job is complete
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Build Output ğŸ‘‡
      uses: actions/download-artifact@v2.1.0
      with:
        name: BuildOutput
        path: ./
    - name: Authorize Google Cloud ğŸ“œ
      id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: Set up Google Cloud SDK â˜
      id: 'gcloud-setup'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: Deploy to Google Cloud App Engine ğŸš€
      id: 'deploy'
      run: |
        ls
        pwd
        cd ./online-shopping-website/frontend/
        gcloud app deploy frontend.yaml --version ${{ github.run_number }} --project ${{ secrets.GCP_PROJECT }}

#     - name: Deploy to Google Cloud App Engine ğŸš€
#       id: 'deploy'
#       uses: 'google-github-actions/deploy-appengine@v0'
#       with:
#         working_directory: ${{ github.workspace }}/online-shopping-website/frontend/
#         deliverables: frontend.yaml
#         promote: true
#         version: ${{ github.run_number }}
        

